### ISSUE TITLE
Bugfix Request: Bernales's Frontend Refresher Project

### ISSUE THREAD

**Issue by jobb-rodriguez** [MaxineNicole2127/webdev-frontend-practice#7]
After 1440px, the CSS disappears.

<img width="1512" alt="Screenshot 2023-12-10 at 7 56 57 AM" src="https://github.com/MaxineNicole2127/webdev-frontend-practice/assets/76737172/ecb117fb-e611-479c-978f-8e27d7058e23">

**Comment by MaxineNicole2127** [comment]
Hi Kuya Jobb! Thank you po for reviewing our work. About po sa disappearing CSS after 1440px, I was conflicted about whether to add a max-width of 1440 because my screen size is 1920px. But, I based it po sa instructions nyo sa vid. I will revise it po later though. Thank you po ulit!
![image](https://github.com/MaxineNicole2127/webdev-frontend-practice/assets/97998223/ead3070b-865a-46d7-8e4e-9a44e02f88be)

**Comment by jobb-rodriguez** [comment]
I see, I see. Sorry for not explaining the whole context in the video.

I used [Quasar's Breakpoints](https://quasar.dev/style/breakpoints/) as my guide.

Attaching the image for your reference.

<img width="782" alt="Screenshot 2023-12-10 at 11 48 37 AM" src="https://github.com/MaxineNicole2127/webdev-frontend-practice/assets/76737172/e8432f3b-f35a-4044-9c9c-f94c291b6955">
